"""Campaign showcase catalog for landing page premium panel."""

CAMPAIGN_STEPS = [
    {
        "id": "dashboard",
        "icon": "📊",
        "kicker": "Command center",
        "title": "Campaign Command Center",
        "short": "Manage and track every automated calling program from one workspace.",
        "desc": "The campaigns dashboard is your operations hub — search programs, filter by status, and see progress, success rates, and agent assignments without switching tools.",
        "detail": "Teams running Mudita Demo, sales outreach, or support lines all land here. Status pills, progress bars, and per-campaign controls stay in sync with live dialer activity.",
        "points": [
            "Search campaigns and filter by status, display, or time range",
            "See flow, assigned agent, progress, and success rate per row",
            "Manage Flows and Create Campaign actions always one click away",
        ],
        "outcomes": ["Live status", "Progress bars", "Success rates", "Agent sync"],
        "usecases": ["Sales outreach", "Demo programs", "Support lines", "Multi-team ops"],
        "flow": ["Search", "Filter", "Assign", "Monitor"],
        "shot": "assets/campaigns/campaigns-dashboard.png",
        "shot_alt": "EMAAVY campaigns dashboard — status, progress, and agent assignment",
    },
    {
        "id": "outbound",
        "icon": "📞",
        "kicker": "Outbound",
        "title": "Outbound Campaigns",
        "short": "Proactive dial programs for sales, lead-gen, surveys, and follow-ups.",
        "desc": "Your agents call a contact list on your schedule. Upload CSV or Excel, pick an agent and flow, and launch high-volume outbound with completion tracking built in.",
        "detail": "Outbound workflows unlock audience upload, pacing controls, and disposition logging. Ideal for Q4 sales outreach, exhibition invites, and payment reminders at scale.",
        "points": [
            "Upload a CSV or Excel contact list",
            "Schedule when calls run and tag by program type",
            "Track completion, outcomes, and success rate live",
        ],
        "outcomes": ["CSV upload", "Scheduled dials", "Outcome tracking", "Tagging"],
        "usecases": ["Lead generation", "Sales outreach", "Surveys", "Follow-ups"],
        "flow": ["Upload list", "Assign agent", "Schedule", "Dial"],
        "shot": "assets/campaigns/create-campaign-type.png",
        "shot_alt": "EMAAVY create campaign — choose outbound type",
    },
    {
        "id": "inbound",
        "icon": "📲",
        "kicker": "Inbound",
        "title": "Inbound Campaigns",
        "short": "24/7 AI lines for support, helpdesk, FAQ, and onboarding.",
        "desc": "Customers call you — no contact list required. Assign a DID, wire your agent and flow, and let EMAAVY answer every ring with natural voice intelligence.",
        "detail": "Inbound programs like Gillete Support run continuously. Supervisors pause or resume lines, swap agents, and monitor answer rates without rebuilding telephony.",
        "points": [
            "No contact list needed — customers call your DID",
            "Assign numbers and route to the right agent profile",
            "AI agent responds 24/7 with playbook-grounded answers",
        ],
        "outcomes": ["DID routing", "24/7 answer", "No upload", "Live control"],
        "usecases": ["Customer support", "Helpdesk", "FAQ lines", "Onboarding"],
        "flow": ["Assign DID", "Wire agent", "Go live", "Monitor"],
        "shot": "assets/campaigns/create-campaign-type.png",
        "shot_alt": "EMAAVY create campaign — choose inbound type",
    },
    {
        "id": "wizard",
        "icon": "🧭",
        "kicker": "5-step wizard",
        "title": "Five-Step Guided Wizard",
        "short": "Configure audience, agent, flow, call settings, and launch with a live preview.",
        "desc": "EMAAVY walks teams through five guided steps — name the campaign, upload contacts, assign agents, set call rules, and launch — while a side preview updates in real time.",
        "detail": "Campaign basics, tags, and contact upload happen in step one. Agent, flow, and telephony settings follow with the same wizard chrome your product team already uses.",
        "points": [
            "Audience → Agent → Flow → Call Settings → Launch",
            "Campaign preview updates as you type and tag",
            "Outbound and inbound paths adapt automatically",
        ],
        "outcomes": ["Live preview", "Guided steps", "Tagging", "Fast setup"],
        "usecases": ["First-time launch", "Enterprise rollout", "Agency programs", "Pilot campaigns"],
        "flow": ["Audience", "Agent", "Flow", "Settings", "Launch"],
        "shot": "assets/campaigns/create-campaign-audience.png",
        "shot_alt": "EMAAVY campaign wizard — audience and preview panel",
    },
    {
        "id": "operations",
        "icon": "▶️",
        "kicker": "Live ops",
        "title": "Live Campaign Control",
        "short": "Pause, resume, or stop programs mid-flight with real-time metrics.",
        "desc": "Supervisors control active campaigns without leaving the dashboard — play, pause, and stop buttons per row, plus progress numerators and success-rate alerts.",
        "detail": "See Mudita Demo go active, Test prady pause mid-run, or sales outreach cancel cleanly. Every action reflects in progress bars and disposition feeds instantly.",
        "points": [
            "Pause, play, and stop controls on every campaign row",
            "Progress tracking — contacts completed vs total",
            "Success rate and warning indicators for at-risk programs",
        ],
        "outcomes": ["Play/pause/stop", "0/N progress", "Success %", "Supervisor ready"],
        "usecases": ["Live demos", "Paused pilots", "Support surges", "Compliance holds"],
        "flow": ["Monitor", "Pause", "Adjust", "Resume"],
        "shot": "assets/campaigns/campaigns-dashboard.png",
        "shot_alt": "EMAAVY campaigns — live status and control actions",
    },
]

# Fixed orbit positions (same layout as integration 5-node hub)
NODE_LAYOUT = {
    "dashboard": (50.0, 18.0),
    "outbound": (82.0, 28.0),
    "inbound": (82.0, 72.0),
    "wizard": (18.0, 72.0),
    "operations": (18.0, 28.0),
}
