"""Call lifecycle showcase catalog for landing page premium panel."""

LIFECYCLE_STEPS = [
    {
        "id": "ring",
        "icon": "📞",
        "kicker": "Ring",
        "title": "Ring — Call Connects",
        "short": "The lifecycle begins the moment the call connects — zero warm-up delay.",
        "desc": "EMAAVY starts listening immediately when a call answers. No dropped opening seconds, no intelligence lost before the first hello — inbound, outbound, or supervisor-monitored.",
        "detail": "Ring is the ingest stage. EMAAVY attaches to the audio stream at connect and enriches it with caller ID, campaign tags, and consent state before transcription even starts.",
        "points": [
            "Audio capture begins at answer — inbound or outbound",
            "Caller ID, dialed number, and campaign ID logged to the session",
            "Recording consent and regional compliance flags applied",
            "Speaker context initialized for diarization downstream",
        ],
        "outcomes": ["0ms delay", "100% capture", "Full metadata", "Compliance ready"],
        "usecases": ["Inbound support", "Outbound campaigns", "Supervised sales", "Regulated lines"],
        "flow": ["Connect", "Tag", "Record", "Stream"],
        "stats": [("0ms", "Start delay"), ("100%", "Capture rate"), ("Instant", "Metadata")],
        "page": "pages/call-lifecycle/ring.html",
    },
    {
        "id": "transcribe",
        "icon": "🎙️",
        "kicker": "Transcribe",
        "title": "Transcribe — Every Word Captured",
        "short": "Sub-500ms streaming STT on the wire — not a post-call report.",
        "desc": "EMAAVY streams every word through your chosen STT stack — Deepgram for international accents, Sarvam for Indian languages — with sub-half-second word latency while the conversation is still live.",
        "detail": "Supervisors, AI agents, and scoring models all consume the same live transcript — eliminating the batch-processing blind spot that plagues traditional call centers.",
        "points": [
            "Partial transcripts appear word-by-word in the intelligence layer",
            "Speaker diarization separates agent, customer, and AI voices",
            "Confidence scores attach to each token for QA review",
            "Live keyword detection can trigger supervisor alerts mid-call",
        ],
        "outcomes": ["<500ms STT", "Diarization", "Live keywords", "QA confidence"],
        "usecases": ["Live coaching", "AI agent context", "QA automation", "Multi-language"],
        "flow": ["Stream", "Diarize", "Score", "Alert"],
        "stats": [("<500ms", "Word latency"), ("22", "Languages"), ("Live", "Partial text")],
        "page": "pages/call-lifecycle/transcribe.html",
    },
    {
        "id": "analyze",
        "icon": "🧠",
        "kicker": "Analyze",
        "title": "Analyze — Score Live",
        "short": "Sentiment, intent, and risk update per turn — not overnight batch jobs.",
        "desc": "Analysis happens on every conversational turn. Sentiment arcs, buyer intent, objection types, and compliance risk update live so teams can act before the caller hangs up.",
        "detail": "Your configured LLM stack interprets meaning, emotion, and risk on each turn, feeding intelligence dashboards and the trigger engine simultaneously.",
        "points": [
            "Sentiment timeline shifts green, amber, or red as tone changes",
            "Intent classified as buy, explore, objection, or reject per turn",
            "Compliance lexicon flags risky phrases for regulated industries",
            "Objection tags feed script coaching and funnel analytics",
        ],
        "outcomes": ["Live sentiment", "Intent scoring", "Compliance flags", "Objection tags"],
        "usecases": ["Sales qualification", "Compliance monitoring", "Deal rescue", "Funnel analytics"],
        "flow": ["Sentiment", "Intent", "Compliance", "Objections"],
        "stats": [("Per turn", "Analysis"), ("Live", "Intent score"), ("Risk", "Alerts")],
        "page": "pages/call-lifecycle/analyze.html",
    },
    {
        "id": "act",
        "icon": "⚡",
        "kicker": "Act",
        "title": "Act — Triggers Fire",
        "short": "CRM, WhatsApp, calendars, and webhooks — fired from what was actually said.",
        "desc": "Intelligence without action is noise. The Act stage fires CRM updates, WhatsApp confirmations, Cal.com bookings, coaching pings, and custom webhooks automatically during and after the call.",
        "detail": "Business rules map conversation signals to downstream systems — so operations teams stop copying notes and developers stop polling for transcripts.",
        "points": [
            "CRM disposition and custom fields update on call end or mid-call",
            "WhatsApp and email follow-ups send with personalized context",
            "Calendar events create when the agent books a slot live",
            "Supervisor coaching alerts fire on negative sentiment shifts",
        ],
        "outcomes": ["CRM sync", "WhatsApp follow-up", "Calendar booking", "Coach alerts"],
        "usecases": ["Revenue ops", "Support tickets", "Post-call nurture", "Supervisor handoff"],
        "flow": ["CRM", "WhatsApp", "Calendar", "Webhooks"],
        "stats": [("Auto", "CRM updates"), ("Live", "Triggers"), ("0", "Copy-paste")],
        "page": "pages/call-lifecycle/act.html",
    },
    {
        "id": "learn",
        "icon": "📈",
        "kicker": "Learn",
        "title": "Learn — Models Improve",
        "short": "Every outcome feeds the next campaign — compounding performance over time.",
        "desc": "The lifecycle closes with learning. Every conversation feeds script A/B results, model routing refinements, and coaching patterns — so the next campaign performs better than the last.",
        "detail": "EMAAVY aggregates outcomes across campaigns to recommend script changes, STT/LLM routing tweaks, and agent coaching focus areas — without a separate data science team.",
        "points": [
            "Script variants ranked by conversion and handle time",
            "Model routing adjusted for language and intent segments",
            "Coaching patterns surfaced for under-performing agents",
            "Funnel trends exported for executive and ops reviews",
        ],
        "outcomes": ["Script A/B", "Model routing", "Coaching data", "Funnel exports"],
        "usecases": ["Quarterly gains", "Cost per outcome", "Data-led coaching", "Executive reviews"],
        "flow": ["Rank", "Route", "Coach", "Export"],
        "stats": [("QoQ", "Conversion lift"), ("Auto", "Routing"), ("Closed", "Loop")],
        "page": "pages/call-lifecycle/learn.html",
    },
]

NODE_LAYOUT = {
    "ring": (50.0, 18.0),
    "transcribe": (82.0, 28.0),
    "analyze": (82.0, 72.0),
    "act": (18.0, 72.0),
    "learn": (18.0, 28.0),
}
